### PR TITLE
fix ASCII backslash encoding

### PR DESCRIPTION
**Pull request by juliangut**
Fix covering https://github.com/farhadi/node-smpp/issues/148

### CODE REVIEW

**Comment by juliangut** [comment]
@polsumeet3666 have you had time to review this PR?

**Comment by juliangut** [comment]
I'm going to hold this PR till we have confirmation from @polsumeet3666

**Review by polsumeet3666 — APPROVED** [review]
Backslash character is delivered to handset. issue has be resolved. tested with my SMSC

**Comment by juliangut** [comment]
Great!

merging

**Pull request merged**
